version: '3'
services:
  webapp:
    image: myapp:latest
    expose:
      - "8080"
    environment:
      REDIRECT_URL: "http://localhost:4180"

  webapp2:
    image: myapp:latest
    expose:
      - "8080"
    environment:
      REDIRECT_URL: "http://localhost:4181"

  oauth2-proxy-4180:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - "4180:8080"
    environment:
      OAUTH2_PROXY_PROVIDER: "google"
      OAUTH2_PROXY_CLIENT_ID: "Chnage_me"
      OAUTH2_PROXY_CLIENT_SECRET: "Chnage_me"
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost:4180/oauth2/callback"
      OAUTH2_PROXY_UPSTREAMS: "http://webapp:8080/"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:8080"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_SECRET: "thisismysecretkeyfortestingmyapp"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_SAMESITE: "lax"

  oauth2-proxy-4181:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - "4181:8080"
    environment:
      OAUTH2_PROXY_PROVIDER: "google"
      OAUTH2_PROXY_CLIENT_ID: "Chnage_me"
      OAUTH2_PROXY_CLIENT_SECRET: "Chnage_me"
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost:4181/oauth2/callback"
      OAUTH2_PROXY_UPSTREAMS: "http://webapp2:8080/"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:8080"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_SECRET: "thisismysecretkeyfortestingmyapp"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_SAMESITE: "lax"